### PR TITLE
get name from the eus model if the argument name is not passed

### PR DESCRIPTION
**Pull request by mmurooka**
eusモデルをurdfに変換するスクリプトを微修正しました．

### CODE REVIEW

**Comment by mmurooka** [comment]
Cloud you review and merge if no problem?

**Comment by k-okada** [comment]
please rebase origin/master

**Comment by k-okada** [comment]
I still have doubt on supporting eus->urdf converter because I can not  take responsibility for this, so 
1) please add test code for this
2) please add your name to maintainer

**Comment by mmurooka** [comment]
> I still have doubt on supporting eus->urdf converter because I can not take responsibility for this, so
1) please add test code for this
2) please add your name to maintainer

I agree with supporting eus->urdf converter so I will make another PR and do 1) and 2).
But before that, I'd like to double check that these codes are originally added by NOT only my opinion but discussing with some major JSK members. cf. https://github.com/jsk-ros-pkg/jsk_demos/pull/988#issuecomment-118694277

**Comment by mmurooka** [comment]
Travis passed. Commit of test code is merged and test passed. Cloud you merge?

**Pull request merged**
