### PR TITLE
[eusurdf] remove rosbuild related scripts

### PR DESCRIPTION
**Pull request by furushchev**
This PR remove rosbuild related scripts, these codes are now not used any more.
- [eusurdf] remove rosbuild related scripts

This will solve the problem of https://github.com/jsk-ros-pkg/jsk_model_tools/pull/132

### CODE REVIEW

**Comment by k-okada** [comment]
please do not update .travis unless you really needed

**Comment by k-okada** [comment]
if you neede, please write as `update to version x.x of jsk_travis`, so we can understand if someone rollback to previous version

**Comment by k-okada** [comment]
gi

**Comment by furushchev** [comment]
@k-okada sorry it is just my habit.

**Pull request merged**
