### PR TITLE
[eusurdf] Use collada_urdf instead of collada_urdf_jsk_patch

### PR DESCRIPTION
**Pull request by wkentaro**

### CODE REVIEW

**Comment by k-okada** [comment]
I think we need collada_urdf_jsk_patch for some reason @YoheiKakiuchi

**Comment by YoheiKakiuchi** [comment]
https://github.com/jsk-ros-pkg/jsk_common/pull/557
@mmurooka 
Do we still need collada_urdf_jsk_patch ?

**Comment by mmurooka** [comment]
Last check was Hydro @ May, 2014. cf. https://github.com/start-jsk/rtmros_gazebo/issues/48#issuecomment-41999914
I'll check again with new environment, but if supporting hydro, I think that keeping to use collada_urdf_jsk_patch is safe.

**Comment by wkentaro** [comment]
I confirmed using collada_to_urdf in collada_urdf package does not work to spawn models on Gazebo correctly, and `collada_urdf_to_jsk_patch` is still required. I tested with room73b2 models.

**Comment by wkentaro** [comment]
So closing at this time.

**Comment by k-okada** [comment]
so we need to wait for assimp 3.2 ? @yoheikakiuchi
https://launchpad.net/ubuntu/+source/assimp

--
◉ Kei Okada

**Pull request closed without merging**
