### PR TITLE
[eusurdf] generate ontology file for jsk room

### PR DESCRIPTION
**Pull request by furushchev**

### CODE REVIEW

**Comment by furushchev** [comment]
requires #188 #189

**Comment by mmurooka** [comment]
Conversion flow from eus to urdf changed? Cloud you explain in detail?

**Comment by furushchev** [comment]
@mmurooka This pull request is for srdl model generation. Let's discuss at https://github.com/jsk-ros-pkg/jsk_model_tools/pull/188

**Comment by furushchev** [comment]
overtaken by #194

**Pull request closed without merging**
