### PR TITLE
[eusurdf] delete manifest.xml for gazebo model directory

### PR DESCRIPTION
**Pull request by mmurooka**
manifest.xml in gazebo model directory is not necessary now.
cc: @wkentaro

### CODE REVIEW

**Comment by wkentaro** [comment]
@mmurooka 
why not add `.gitignore` to `eusurdf/models` dir to keep it?

`eusurdf/models/.gitignore`
```
*
!.gitignore
```

**Comment by mmurooka** [comment]
added.

**Comment by wkentaro** [comment]
So aaefc74 is not necessary, isn't it?

**Comment by mmurooka** [comment]
あってもいい気もするけれど，なくしたほうがいい？

**Comment by wkentaro** [comment]
確かにどっちでもいいので、個人の趣味ですね。

**Pull request merged**
