### PR TITLE
[euscollada] Add script to remove link from urdf

### PR DESCRIPTION
**Pull request by garaemon**

### CODE REVIEW

**Comment by k-okada** [comment]
did you commit only pyc, not py?

**Comment by garaemon** [comment]
wow, sorry.. I fix it

✉︎ Ryohei

**Comment by garaemon** [comment]
Fixed

2015年1月28日水曜日、Ryohei Ueda<garaemon@gmail.com>さんは書きました:

> wow, sorry.. I fix it
>
> ✉︎ Ryohei
>
>
>
> On Wed, Jan 28, 2015 at 8:28 AM, Kei Okada <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> did you commit only pyc, not py?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/jsk-ros-pkg/jsk_model_tools/pull/92#issuecomment-71751097>
>> .
>>
>
>

-- 
from iPhone

**Comment by YoheiKakiuchi** [comment]
Is it fixed?
please commit remove_sensor_from_urdf.py

**Comment by garaemon** [comment]
I found that I removed remove_sensor_from_urdf.pyc and added add_sensor_from_urdf.pyc ... sigh...

**Pull request merged**
