### PR TITLE
[eusurdf] add hooks for setting environment variables for gazebo

### PR DESCRIPTION
**Pull request by furushchev**

### CODE REVIEW

**Comment by k-okada** [comment]
you can use gazebo_media_path option of export tag.

http://answers.gazebosim.org/question/7805/is-it-possible-to-add-custom-texture-file/

**Comment by furushchev** [comment]
@k-okada hmm, I don't know it's right way, but I think it does not work.

package.xml In jsk_pr2_startup (which contains `pr2_gazebo.launch`):

```bash
  <export>
    <rqt_gui plugin="${prefix}/plugin.xml"/>
    <gazebo_ros
        gazebo_media_path="$(rospack find eusurdf)"
        gazebo_model_path="$(rospack find eusurdf)/models" />
  </export>
```

and checked:

```bash
$ rospack export --lang=gazebo_ros --attrib=gazebo_media_path jsk_pr2_startup
/home/furushchev/ros/hydro/src/jsk-ros-pkg/jsk_model_tools/eusurdf
```

but when I executed:

```bash
roslaunch jsk_pr2_startup pr2_gazebo.launch world:=`rospack find eusurdf`/worlds/room610.world
```

gazebo could not resolve model paths.

As far as I searched source code, available attributes are `gazebo_media_path`, `plugin_path`, `gazebo_model_path`:
https://github.com/ros-simulation/gazebo_ros_pkgs/blob/hydro-devel/gazebo_ros/src/gazebo_ros_paths_plugin.cpp#L60-L97
but it seems not  to be enabled.
Also there is no way to set `GAZEBO_RESOURCE_PATH` with package.xml
So we need env-hooks anyway.

**Comment by k-okada** [comment]
use ${prefix}, package.xml is not shell script so you can not use $(rospack
find...)

https://github.com/tork-a/hakuto/blob/master/tetris_gazebo/package.xml may
help you to understand




--
◉ Kei Okada

**Comment by furushchev** [comment]
Yes, but eusurdf is in different repo from jsk_pr2_startup. and I don't know how to use prefix of different pkgs.As I checked source, at <export> tag, we can use shell script https://github.com/ros/rospack/blob/indigo-devel/src/rospack.cpp#L2138

Outlook から送信されました




On Thu, Jul 30, 2015 at 4:05 AM -0700, "Kei Okada" <notifications@github.com> wrote:










use ${prefix}, package.xml is not shell script so you can not use $(rospack

find...)



https://github.com/tork-a/hakuto/blob/master/tetris_gazebo/package.xml may

help you to understand









--

◉ Kei Okada





On Thu, Jul 30, 2015 at 7:56 PM, Furushchev <notifications@github.com>

wrote:

**Comment by k-okada** [comment]
export is export, so if your package depends other package with export,
then you can use that information

--
◉ Kei Okada

**Comment by furushchev** [comment]
please merge after #134

**Pull request merged**
