### PR TITLE
[eusurdf] get path of the roseus execute file in CMakeList.txt

### PR DESCRIPTION
**Pull request by mmurooka**
https://github.com/jsk-ros-pkg/jsk_model_tools/pull/158#issuecomment-160045097

### CODE REVIEW

**Comment by garaemon** [comment]
roseus is run_depend

**Comment by mmurooka** [comment]
> roseus is run_depend

added roseus to build_depend.

**Comment by k-okada** [comment]
can you try if this works with following command ?

## Do not source setup.bash before hand, make sure you can not run
roseus nor rosrun command at this moment.

bloom-generate rosdebian --os-name ubuntu --os-version trusty
--ros-distro indigo
fakeroot debian/rules binary

--
◉ Kei Okada

**Comment by mmurooka** [comment]
https://github.com/jsk-ros-pkg/jsk_model_tools/pull/164 resolves the problem of deb package build.

**Pull request closed without merging**
