### PR TITLE
[euscollada] Support passing limbs to predefined pose method

### PR DESCRIPTION
**Pull request by wkentaro**
Modified:
  - euscollada/src/collada2eus.cpp

### CODE REVIEW

**Comment by wkentaro** [comment]
to allow
```
(send *robot* :reset-pose :rarm)
```

**Comment by wkentaro** [comment]
Could you please review and merge?

**Comment by k-okada** [comment]
@YoheiKakiuchi

--
◉ Kei Okada

**Comment by wkentaro** [comment]
Below is robot model generated with this commit:

- jsk_2015_05_baxter_apc customized Baxter (https://gist.github.com/ac68f2998ce84adb22dd7393abde385c)
- baxter v1.2.0 (https://gist.github.com/bd164fc0497e118e6517499fcdf0e01d)

**Comment by YoheiKakiuchi** [comment]
Could you please take care about readability.
Generated code may be like this.
```
    (:reset-pose
     (&optional (limbs '(:rleg :lleg :torso :head :rarm :larm)))
     (unless (listp limbs) (setq limbs (list limbs)))
     (dolist (limb limbs)
       (case limb
         (:rleg (send self limb :angle-vector (float-vector 0.000000 0.000000 -26.000000 50.000000 -24.000000 0.000000 0.000000)))
         (:lleg (send self limb :angle-vector (float-vector 0.000000 0.000000 -26.000000 50.000000 -24.000000 0.000000 0.000000)))
         (:torso (send self limb :angle-vector (float-vector 0.000000 0.000000)))
         (:head (send self limb :angle-vector (float-vector 0.000000 0.000000)))
         (:rarm (send self limb :angle-vector (float-vector 10.000000 -10.000000 0.000000 -25.000000 0.000000 0.000000 -10.000000 15.000000)))
         (:larm (send self limb :angle-vector (float-vector 10.000000 10.000000 0.000000 -25.000000 0.000000 0.000000 -10.000000 -15.000000)))
         (t (format t "Unknown limb is passed: ~a~%" limb))))
     (send self :angle-vector))
```

**Comment by wkentaro** [comment]
@YoheiKakiuchi 
Thank you for the review. I have updated the commit.

**Comment by k-okada** [comment]
Did you confirm if this work for robot like one arm/leg, such as Pepper or Fetch?

I feel it's much safer to update code like
;; if limb is not given
(send self :angle-vector #f(....))
;; else 
(dolist ...

Or is this too redundant?

--
◉ Kei Okada

2016/04/11 18:32、Yohei Kakiuchi <notifications@github.com> のメッセージ:

**Comment by wkentaro** [comment]
@k-okada 
> Did you confirm if this work for robot like one arm/leg, such as Pepper or Fetch?[

I think it works, because they don't have only one limb, like (:rarm, :head, :torso for Fetch).

```
$ roseus fetch.l
2.irteusgl$ send *fetch* :reset-pose
#f(2.86479 75.6304 80.2141 -11.4592 98.5487 0.0 95.111 0.0 0.0 0.0)
3.irteusgl$ send *fetch* :reset-pose :rarm
#f(2.86479 75.6304 80.2141 -11.4592 98.5487 0.0 95.111 0.0 0.0 0.0)
4.irteusgl$ send *fetch* :reset-pose :larm
Unknown limb is passed: :larm
#f(2.86479 75.6304 80.2141 -11.4592 98.5487 0.0 95.111 0.0 0.0 0.0)
5.irteusgl$ send *fetch* :reset-pose :head
#f(2.86479 75.6304 80.2141 -11.4592 98.5487 0.0 95.111 0.0 0.0 0.0)
```
```
$ grep ':reset-pose (&optional' fetch.l -A8
    (:reset-pose (&optional (limbs '(:torso :rarm :head)))
      (unless (listp limbs) (setq limbs (list limbs)))
      (dolist (limb limbs)
        (case limb
          (:torso (send self limb :angle-vector (float-vector 2.864790)))
          (:rarm (send self limb :angle-vector (float-vector 75.630400 80.214100 -11.459200 98.548700 0.000000 95.111000 0.000000)))
          (:head (send self limb :angle-vector (float-vector 0.000000 0.000000)))
          (t (format t "Unknown limb is passed: ~a~%" limb))))
      (send self :angle-vector))
```

**Comment by snozawa** [comment]
It would be nice to add:
- documentation string for `:reset-pose` to indicate how to use this method
- test codes for typical JSK robots, such as a two-armed robot (pr2, baxter), a one-armed-one-legged robot (pepper), and a two-armed-two-legged robot (hrp2,jaxon).

**Comment by wkentaro** [comment]
@YoheiKakiuchi @snozawa
As the author of pr2.sh, nao.sh and darwin.sh, do you know how to run these test scripts with `catkin run_tests` command?
I'm looking for cmake function to run shell script as test, like [roslaunch_add_file_check](https://github.com/ros/ros_comm/blob/kinetic-devel/tools/roslaunch/cmake/roslaunch-extras.cmake.em#L24) do for roslauch file.

**Comment by wkentaro** [comment]
I added a simple tool for this. https://github.com/jsk-ros-pkg/jsk_common/pull/1371
And added the test: https://github.com/jsk-ros-pkg/jsk_model_tools/pull/175

**Pull request merged**
