### PR TITLE
package.xml; we nee do rosrun to generate models

### PR DESCRIPTION
**Pull request by k-okada**
@mmurooka

http://jenkins.ros.org/job/ros-indigo-eusurdf_binarydeb_trusty_amd64/18/console

### CODE REVIEW

**Comment by mmurooka** [comment]
Thank you.

**Comment by k-okada** [comment]
humm, it still fails may be we'd better not to use rosrun during compile phase
http://jenkins.ros.org/job/ros-indigo-eusurdf_binarydeb_saucy_i386/18/console

**Comment by mmurooka** [comment]
I'd like to call roseus in compile.
https://github.com/jsk-ros-pkg/jsk_model_tools/blob/master/eusurdf/scripts/convert-scene-to-urdf.py#L21
Is there any example to call roseus without rosrun?

**Comment by k-okada** [comment]
roseus can run without calling rosrun , try `roseus` on your terminal

**Comment by mmurooka** [comment]
I tried and rosrun is not needed.
I created PR: https://github.com/jsk-ros-pkg/jsk_model_tools/pull/159.

**Comment by k-okada** [comment]
But maybe it still fails, because build firms running without sourcing
setup.bash

Why did previous virsion pass the Jenkins build firm. What did you changed?

2015年11月27日金曜日、Masaki Murooka<notifications@github.com>さんは書きました:

> I'd like to call roseus in compile.
>
> https://github.com/jsk-ros-pkg/jsk_model_tools/blob/master/eusurdf/scripts/convert-scene-to-urdf.py#L21
> Is there any example to call roseus without rosrun?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_model_tools/pull/158#issuecomment-160041733>
> .
>


-- 
--
◉ Kei Okada

**Comment by mmurooka** [comment]
I don't know.. Maybe I don't change eusurdf recently.

**Comment by k-okada** [comment]
0.1.13 was ok but 2.0.0 was failed and you're only person who changed the source code

```

 -- Kei Okada <k-okada@jsk.t.u-tokyo.ac.jp>  Thu, 26 Nov 2015 15:00:00 -0000

ros-indigo-eusurdf (0.2.0-0saucy) saucy; urgency=high

  * move to 0.2.0, which only available from indigo
  * add instruction of converting eus->urdf
  * modify sample usage comment of irteus2urdf-for-gazebo.
  * use the resolved path of ros package to find eusurdf directory when path is nil. You can pass eusurdf path as argument to run in catkin build.
  * add .gitignore to keep model directory
  * generate model directory if not found.
  * delete manifest.xml for gazebo model directory.
  * Contributors: Masaki Murooka

 -- Kei Okada <k-okada@jsk.t.u-tokyo.ac.jp>  Wed, 25 Nov 2015 15:00:00 -0000

ros-indigo-eusurdf (0.1.13-0saucy) saucy; urgency=high
```

**Comment by k-okada** [comment]
you can find this information at 
http://jenkins.ros.org/job/ros-indigo-eusurdf_binarydeb_trusty_amd64/18/console

**Comment by k-okada** [comment]
http://jenkins.ros.org/job/ros-indigo-eusurdf_sourcedeb/

--
◉ Kei Okada

2015/11/27 14:03、Masaki Murooka <notifications@github.com> のメッセージ:

**Comment by mmurooka** [comment]
Hmm, `rosrun roseus roseus` should be called in 0.1.13 and it was succeeded.
https://github.com/jsk-ros-pkg/jsk_model_tools/blame/master/eusurdf/scripts/convert-scene-to-urdf.py
I have no idea.

Can I create a PR to pass the absolute path of roseus, like https://github.com/jsk-ros-pkg/jsk_model_tools/blob/master/eusurdf/CMakeLists.txt#L9-L16?

**Comment by k-okada** [comment]
released new version and now succeeded to build deb file http://jenkins.ros.org/job/ros-indigo-eusurdf_sourcedeb/

**Comment by mmurooka** [comment]
Thank you.

**Pull request merged**
